# Main branch CI Pipeline

name: MainCI_$(Year:yyyy).$(Month).$(Rev:r)    

trigger: none

variables:
  buildConfiguration: 'Release'
  prerelease: 'ci'
  moduleName: 'Algorand.MainCI'
  guid: '1d904a83-6e54-480a-87fa-02ea0aac36e0'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Update assembly info'
  inputs:
    Path: '$(Build.SourcesDirectory)/src/'
    FileNames: 'Algorand.PowerShell/Algorand.PowerShell.csproj'
    InsertAttributes: true
    WriteBOM: true
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: 'Build Algorand.PowerShell'
  inputs:
    command: 'publish'
    projects: 'src/Algorand.PowerShell/Algorand.PowerShell.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(moduleName) --no-self-contained'
    modifyOutputPath: false
    publishWebProjects: false
    zipAfterPublish: false

- task: PowerShell@2
  displayName: 'Create Module Manifest'
  inputs:
    pwsh: true
    targetType: 'filePath'
    filePath: 'src/create-module-manifest.ps1'
    arguments: >
        -Path "$(Build.ArtifactStagingDirectory)/$(moduleName)"
        -Prerelease "$(prerelease)"
        -Guid "$(guid)"
    errorActionPreference: 'stop'

- task: DotNetCoreCLI@2
  displayName: 'Test Algorand.PowerShell: Unit Tests'
  inputs:
    command: 'test'
    projects: 'test/Algorand.PowerShell.UnitTest/Algorand.PowerShell.UnitTest.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Algorand.PowerShell artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'